[tool.poetry]
name = "noaa-goes-downloader"
version = "0.1.0"
description = ""
authors = ["Helvecio Leal <helvecio.neto@inpe.br>"]

[tool.poetry.dependencies]
python = "3.9.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
